### ISSUE TITLE
Deprecated problem during "make"

### ISSUE THREAD

**Issue by kayuksel** [peterhj/shiftnet_cuda_v2#2]
python build_ffi.py
Traceback (most recent call last):
  File "build_ffi.py", line 2, in <module>
    from torch.utils.ffi import create_extension
  File "/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Makefile:28: recipe for target 'build/shiftnet_cuda/_shiftnet_cuda.so' failed
make: *** [build/shiftnet_cuda/_shiftnet_cuda.so] Error 1

**Comment by kayuksel** [comment]
Hello, I guess that I managed to compile it with cuda 9.2 and 9.0

However, the test_shifnet gives following error:

  File "test_shiftnet.py", line 4, in <module>
    import shiftnet_cuda
  File "/home/kamer/shiftnet_cuda_v2/shiftnet_cuda/__init__.py", line 3, in <module>
    from ._shiftnet_cuda import lib as _lib, ffi as _ffi
ImportError: /home/kamer/shiftnet_cuda_v2/shiftnet_cuda/_shiftnet_cuda.so: undefined symbol: __cudaPopCallConfiguration

**Comment by euler16** [comment]
which PyTorch version are you using?

**Comment by kayuksel** [comment]
@euler16 I am actually using 1.0.0 now with cuda 10.0; but I have got the mentioned error with the torch 0.4.1 and cuda 9.0 / 9.2 since that was the one where I was able to compile the shiftnet_cuda.so file. Thnx!

**Comment by euler16** [comment]
PyTorch 1.0 has a different cpp extension API now. Try CUDA 9.0 PyTorch 0.4 by making the following changes.

1. In the make file replace 

NVCC_COMPILE := $(NVCC) -arch=sm_30 \
 -gencode=arch=compute_30,code=sm_30 \
 -gencode=arch=compute_50,code=sm_50 \
 -gencode=arch=compute_52,code=sm_52 \
 -gencode=arch=compute_60,code=sm_60 \
 -gencode=arch=compute_61,code=sm_61 \
-gencode=arch=compute_61,code=compute_61 -c -o 

with 

NVCC_COMPILE := $(NVCC)  \
  -gencode=arch=compute_50,code=sm_50 \
  -gencode=arch=compute_52,code=sm_52 \
  -gencode=arch=compute_60,code=sm_60 \
  -gencode=arch=compute_61,code=sm_61 \
  -gencode=arch=compute_70,code=sm_70 \
  -gencode=arch=compute_70,code=compute_70 -c -o

make sure NVCC variable in the makefile points to your CUDA 9 nvcc.

The issue I think is due to incorrect architecture specification. Read [here](https://docs.nvidia.com/cuda/volta-compatibility-guide/index.html)

P.S I haven't tried the solution myself , but only this part seems to be the issue since the kernel code is perfectly GPU agnostic.

**Comment by kayuksel** [comment]
Thanks a lot! I also opened an issue at PyTorch repository so that they integrate this. However, they said that they would have to wait until it becomes more popular. The public interest does not seem to be so high yet based on the starts of this repository. They also described me a way to do it using the grid_sample function that is already in PyTorch: https://github.com/pytorch/pytorch/issues/16408

**Comment by kayuksel** [comment]
@euler16 FYI, it resulted in the same error after I experimented with your solution. Thank you anyways.

**Comment by euler16** [comment]
ohh. I am sorry I gave an untested suggestion. I don't have GPU access at the moment

**Comment by euler16** [comment]
@kayuksel if you were able to implement the suggestion given on the PyTorch repo, could you please open source the implementation?

**Comment by qdd1234** [comment]
Hi, I meet the same question. My CUDA version is 11.0, How can I modify the Makefile?
![Uploading image.png…]()

**Comment by qdd1234** [comment]
Hi, I meet the same question. My CUDA version is 11.0, How can I modify the Makefile?
![image](https://user-images.githubusercontent.com/68497831/130228821-93bec5d0-3b77-45e2-8bf9-fbd532fc4e9e.png)
